# Generated by Django 5.2.1 on 2025-05-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_category_menuitem_category_order_cart_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_item_of_the_day",
            field=models.BooleanField(default=False),
        ),
    ]
